from __future__ import annotations
import argparse, json, logging, os, re, subprocess, sys, threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from playwright.sync_api import sync_playwright
from .config import Settings
from .crawler import crawl
from .explorer import explore
from .flows import record_flow
from .generator import generate_spec
from .llm import ModelClient, diagnose_error
from .urls import merge_extra_urls, read_urls

def name(url: str) -> str: return re.sub(r'[^a-z0-9]+', '-', url.lower()).strip('-')[:100]

def _commit_site(settings, log, verb: str) -> None:
    """git-commit the generated spec suite + url list for this site (opt-in via --commit).
    Force-adds past .gitignore so runs/ stays ignored by default."""
    paths = [str(settings.tests_dir), str(settings.urls_file)]
    try:
        subprocess.run(['git', 'add', '-f', *paths], cwd=settings.root, check=False)
        if subprocess.run(['git', 'diff', '--cached', '--quiet'], cwd=settings.root).returncode == 0:
            log.info('COMMIT nothing changed for %s', settings.site); return
        n = sum(1 for _ in settings.tests_dir.glob('*_test.py'))
        msg = f'tests({settings.site}): {verb} {n} spec(s)\n\n[skip ci] generated by website_test_pipeline'
        subprocess.run(['git', 'commit', '-q', '-m', msg], cwd=settings.root, check=False)
        log.info('COMMIT %s spec(s) for %s', n, settings.site)
    except Exception as exc:
        log.warning('COMMIT failed: %s', exc)

def _download_report(settings, log) -> None:
    """Copy the combined report to this machine's Downloads folder (opt-in via --download). Local
    convenience only: there is no "Downloads folder" in a server/API deployment of this pipeline, so this
    never runs unless explicitly asked for, and never touches anything outside the user's home directory."""
    import shutil
    report_dir = settings.artifacts_dir/'report'
    source = next((p for p in (report_dir/'full-report.docx', report_dir/'full-report-new.docx') if p.is_file()), None)
    if source is None:
        log.warning('DOWNLOAD full-report.docx not found in %s; nothing to copy', report_dir); return
    downloads = Path.home()/'Downloads'
    try:
        downloads.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        destination = downloads/f'{settings.site}-report-{stamp}.docx'
        shutil.copy2(source, destination)
        log.info('DOWNLOAD copied %s -> %s', source.name, destination)
    except Exception as exc:
        log.warning('DOWNLOAD failed: %s', exc)

PYTEST_ARTIFACT_ARGS = ['--screenshot=on', '--video=retain-on-failure', '--tracing=retain-on-failure']

# flows.json (record_flow does a read-modify-write with no file locking of its own) is the one piece of
# state every concurrent page-worker touches; one lock around that call is enough to stop one page's write
# from silently clobbering another's, same for the manifest dict every worker updates.
_flows_lock = threading.Lock()
_manifest_lock = threading.Lock()


def _process_one_url(command: str, settings, client, guide, persona, url: str, i: int, total: int, log, manifest: dict) -> None:
    """One page's explore/generate work, run inside its own thread with its own Playwright driver and
    browser - Playwright's sync API is not safe to share across threads, so this does NOT reuse a browser
    opened by the caller; each call here is fully self-contained. Writes manifest['urls'][url] under
    _manifest_lock and touches flows.json only under _flows_lock."""
    from . import progress
    from .authflow import context_kwargs
    progress.report(settings, 'Exploring pages' if command == 'explore' else 'Generating tests', i, total, url)
    log.info('Processing %s', url)
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=settings.headless)
            try:
                context = browser.new_context(**context_kwargs(settings)); page = context.new_page()
                page.set_default_navigation_timeout(settings.navigation_timeout_ms)
                page.goto(url, wait_until='domcontentloaded')
                inventory = explore(page, url, settings.explore_probe_max, log)
                (settings.artifacts_dir/f'{name(url)}.inventory.json').write_text(json.dumps(inventory.__dict__, indent=2, ensure_ascii=False), encoding='utf-8')
                try:
                    with _flows_lock:
                        record_flow(settings.flows_file, url, inventory.primary_flow, log)
                except Exception as exc:
                    log.warning('flows: could not record flow for %s (%s)', url, exc)
                if command == 'generate':
                    output = settings.tests_dir/f'{name(url)}_test.py'; generate_spec(client, guide, persona, inventory, output, log=log)
                    result = {'status': 'generated', 'spec': str(output)}
                else:
                    result = {'status': 'explored'}
                context.close()
            finally:
                browser.close()
    except Exception as exc:
        diagnosis = diagnose_error(getattr(exc, 'status', None), getattr(exc, 'body', ''), str(exc)); log.error('ROOT CAUSE url=%s diagnosis=%s', url, diagnosis)
        result = {'status': 'failed', 'error': str(exc), 'diagnosis': diagnosis}
    with _manifest_lock:
        manifest['urls'][url] = result

def main() -> int:
    parser = argparse.ArgumentParser(description='Explore websites and generate validated Python Playwright smoke tests.')
    parser.add_argument('command', choices=['crawl','generate','explore','propose','verify','flowgen','flows','intents','expand','execute','report','auth','all'], nargs='?', default='generate')
    parser.add_argument('words', nargs='*', help='auth: <url> (sign in / sign up on it, keep the session) | flows: list | show <id> | approve <id> | reject <id> --reason "..." | reset <id> | add "sentence" | edit <i-id> "sentence" | drop <i-id> | intents | coverage [N] | run | judge [id...] (a vision model rates the final screenshot) | (intents: <file>... requirement documents)')
    parser.add_argument('--reason', default='', help='flows reject/approve: why (required to reject)')
    parser.add_argument('--status', default=None, help='flows list: only flows with this status')
    parser.add_argument('--skip', default='', help='flows run: stages to skip, comma separated (intents,expand,verify,flowgen,execute)')
    parser.add_argument('--only', default='', help='flows run: run only these stages')
    parser.add_argument('--failed-only', action='store_true', help='verify: only flows that are candidate or stale (re-check after a site change)')
    parser.add_argument('--combined', action='store_true', help='report: also write a single full-run document')
    parser.add_argument('--inline-appendix', action='store_true', help='report --combined: keep the evidence appendix inside full-report.docx (hundreds of pages) instead of the separate full-report-appendix.docx')
    parser.add_argument('--download', action='store_true', help='report --combined: also copy full-report.docx to this machine\'s Downloads folder, timestamped - a local convenience only, not meant for a server/API deployment of this pipeline')
    parser.add_argument('--rerun', action='store_true', help='report: rerun the generated tests before rendering; default uses the existing test_results.json')
    parser.add_argument('--repair', action='store_true', help='report: after the first run, feed failing tests back to the model, regenerate, and run once more')
    parser.add_argument('--account', default='', help='auth: which login to use when a site has several (default: "default"); names the saved session and the .env keys')
    parser.add_argument('--no-window', action='store_true', help='all: do not open the progress pop-up (timer + bar)')
    parser.add_argument('--ask-human', action='store_true', help='force the CAPTCHA window on (it is on by default whenever a terminal and display are present)')
    parser.add_argument('--no-ask-human', action='store_true', help='never open the CAPTCHA window: forms with a CAPTCHA are skipped and reported as needing a person')
    parser.add_argument('--browser', default='', choices=['', 'chromium', 'firefox', 'webkit'], help='execute / report --rerun / all: run the tests in this browser (default chromium); needs `playwright install <browser>`. Results replace the previous run: set SITE=<name> in .env to keep another workspace')
    parser.add_argument('--device', default='', help='execute / report --rerun / all: emulate a device, e.g. "iPhone 14" (Playwright device name)')
    parser.add_argument('--commit',action='store_true', help='generate/report: git-commit runs/<site>/tests + urls.txt afterwards')
    args = parser.parse_args()
    if args.account:
        os.environ['AUTH_ACCOUNT'] = args.account
    if args.no_ask_human:
        os.environ['WTP_HUMAN'] = 'skip'                  # read by humanstep.human_mode(); inherited by every step `all` starts
    elif args.ask_human:
        os.environ['WTP_HUMAN'] = 'ask'
    if args.browser:
        os.environ['WTP_BROWSER'] = args.browser          # read by pipeline.test_run_args, so every way of running the tests agrees
    if args.device:
        os.environ['WTP_DEVICE'] = args.device
    settings = Settings(); settings.prepare(); logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s', handlers=[logging.FileHandler(settings.artifacts_dir/'generation.log', encoding='utf-8'), logging.StreamHandler()]); log = logging.getLogger('pipeline')
    log.info('WORKSPACE site=%s dir=%s', settings.site, settings.workspace)
    os.environ['WTP_HEURISTICS'] = str(settings.heuristics_file)   # generated specs read the same lists (see heuristics.py)
    from . import heuristics
    for note in heuristics.configure(settings.heuristics_file):
        log.warning('heuristics: %s', note)
    pytest_env = {**os.environ, 'WTP_ARTIFACTS': str(settings.artifacts_dir)}
    from .authflow import context_kwargs, ensure_session, has_session, landing_urls, preflight_session, session_path, wall_handler
    if has_session(settings):
        pytest_env['WTP_STORAGE_STATE'] = str(session_path(settings))
    if args.command == 'crawl':
        if not settings.seed_url:
            log.error('crawl requires SEED_URL in .env'); return 2
        from . import progress
        progress.report(settings, 'Crawling the site', note=settings.seed_url)
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=settings.headless)
            try:
                signed_in = False
                try:
                    first = ensure_session(settings, browser, settings.seed_url, log)      # sign in first, so the crawl sees the logged-in area
                    signed_in = first.status in {'signed-in-env', 'signed-in-popup', 'session-ok'}
                except Exception as exc:
                    log.warning('auth: could not check for a login wall (%s)', str(exc).splitlines()[0][:150])
                page = browser.new_context(**context_kwargs(settings)).new_page()
                discovered = crawl(page, settings.seed_url, settings.crawl_max_depth, settings.crawl_max_pages, log, settings.navigation_timeout_ms,
                                   on_page=wall_handler(settings, log, already_signed_in=signed_in))   # a wall deeper in the site is signed in to as it is met
                for landing in landing_urls(settings):                            # where a sign-in ends up is not linked from the public site
                    if landing not in discovered:
                        more = crawl(page, landing, settings.crawl_max_depth, settings.crawl_max_pages, log, settings.navigation_timeout_ms)
                        log.info('crawl: from the post-login page %s found %d URL(s)', landing, len(more))
                        discovered += [u for u in more if u not in discovered]
                discovered = discovered[:settings.crawl_max_pages]
            finally:
                browser.close()
        discovered = merge_extra_urls(discovered, settings.seed_url, settings.seeds_file, log)
        settings.urls_file.write_text('\n'.join(discovered) + '\n', encoding='utf-8')
        log.info('CRAWL SUMMARY seed=%s discovered=%s file=%s', settings.seed_url, len(discovered), settings.urls_file)
        return 0
    if args.command == 'all':
        # crawl (when SEED_URL is set) -> generate -> flows run -> report --rerun. The report step runs the tests itself,
        # so execute is skipped in the flow chain. Exit 2 (a stage could not run) stops the chain; exit 1 (tests failed) does not.
        base = [sys.executable, '-m', 'website_test_pipeline.cli']
        steps = ([['crawl']] if settings.seed_url else []) + [['generate'], ['flows', 'run', '--skip', ','.join(filter(None, ['execute', args.skip]))], ['report', '--rerun']]
        from . import progress
        weights = {'crawl': 1, 'generate': 4, 'flows': 3, 'report': 3}          # each step's rough share of the total time
        total_w = sum(weights[s[0]] for s in steps); t0 = datetime.now().timestamp(); done_w = 0
        progress.report(settings, 'Starting', note=settings.site)
        if not args.no_window and progress.window_available():
            subprocess.Popen([*base[:2], 'website_test_pipeline.progress_window', str(progress.progress_file(settings))], cwd=settings.root)
        worst = 0
        for step in steps:
            log.info('ALL step: %s', ' '.join(step))
            span = f'{done_w / total_w},{(done_w + weights[step[0]]) / total_w}'
            env = {**os.environ, 'WTP_PROGRESS_SPAN': span, 'WTP_PROGRESS_START': str(t0)}
            code = subprocess.run([*base, *step, *(['--account', args.account] if args.account else [])], cwd=settings.root, env=env).returncode
            done_w += weights[step[0]]
            if code == 2:
                log.error('ALL stopped: "%s" could not run', step[0]); progress.finish(settings, f'Stopped at {step[0]}'); return 2
            worst = max(worst, code)
        progress.finish(settings)
        return worst
    if args.command == 'auth':
        from .authflow import run_auth
        return run_auth(settings, log, args.words[0] if args.words else settings.seed_url)
    if args.command == 'verify':
        from .runner import run_verify
        return run_verify(settings, log, args.words, args.failed_only)
    if args.command == 'flows' and args.words[:1] == ['judge']:
        from .vision import run_judge
        return run_judge(settings, ModelClient(settings, log), log, args.words[1:])
    if args.command == 'flows' and args.words[:1] == ['run']:
        from .pipeline import parse_stage_list, run_chain
        try:
            run_urls = read_urls(settings.urls_file)
        except OSError:
            run_urls = []
        return run_chain(settings, run_urls, log, parse_stage_list(args.skip), parse_stage_list(args.only))
    if args.command == 'flows':
        from .review import run_flows_command
        return run_flows_command(settings, args.words, args.reason, args.status)
    if args.command == 'flowgen':
        from .flowgen import run_flowgen
        return run_flowgen(settings, log)
    urls = read_urls(settings.urls_file)
    if args.command == 'intents':
        if args.words:                                          # intents <file>...: journeys from requirement documents
            from .documents import run_documents
            return run_documents(settings, urls, ModelClient(settings, log), log, args.words)
        from .intents import run_intents
        return run_intents(settings, urls, ModelClient(settings, log), log)
    if args.command == 'expand':
        from .expand import run_expand
        return run_expand(settings, urls, ModelClient(settings, log), log, args.words)
    if args.command == 'propose':
        from .proposer import run_propose
        return run_propose(settings, urls, ModelClient(settings, log), log)
    if args.command == 'execute':
        from .pipeline import run_execute
        if preflight_session(settings, log) == 2:
            return 2
        return run_execute(settings, log)
    if args.command == 'report':
        from . import report as report_mod
        # A report must describe one specific execution.  Re-running implicitly
        # made the displayed report disagree with the run the user had just seen,
        # and also made report generation depend on the live site being available.
        # Use --rerun (or --repair) when a fresh execution is explicitly wanted.
        result = subprocess.CompletedProcess([], 0)
        from . import progress
        progress.report(settings, 'Running tests and building the report')
        if args.rerun or args.repair:
            if preflight_session(settings, log) == 2:
                return 2
            if has_session(settings):
                pytest_env['WTP_STORAGE_STATE'] = str(session_path(settings))
            from .envinfo import capture_browser
            from .pipeline import test_run_args
            capture_browser(settings.artifacts_dir, os.environ.get('WTP_BROWSER') or 'chromium', os.environ.get('WTP_DEVICE', ''))   # record the browser build these results come from
            pw_out = settings.artifacts_dir/'pw'
            pytest_cmd = [sys.executable, '-m', 'pytest', str(settings.tests_dir), '-q', *PYTEST_ARTIFACT_ARGS, f'--output={pw_out}', *test_run_args()]
            result = subprocess.run(pytest_cmd, cwd=settings.root, env=pytest_env)
        elif not (settings.artifacts_dir/'test_results.json').exists():
            log.error('REPORT no existing test_results.json; run execute first or use --rerun')
            return 2
        if args.repair:
            from .failrepair import repair_failures
            manifest = json.loads((settings.artifacts_dir/'run.json').read_text(encoding='utf-8')) if (settings.artifacts_dir/'run.json').exists() else {'urls': {}}
            guide = (settings.root/'AI-TEST-GUIDE.md').read_text(encoding='utf-8') if (settings.root/'AI-TEST-GUIDE.md').exists() else ''
            persona = (settings.root/'persona.txt').read_text(encoding='utf-8') if (settings.root/'persona.txt').exists() else ''
            n = repair_failures(settings.artifacts_dir, settings.tests_dir, manifest, ModelClient(settings, log), guide, persona, log)
            if n:
                log.info('REPAIR regenerated %s page(s); re-running', n)
                result = subprocess.run(pytest_cmd, cwd=settings.root, env=pytest_env)
        if args.rerun or args.repair:
            from .flowresults import feed_results
            feed_results(settings, log)
        run = report_mod.create_report(settings.artifacts_dir, settings.tests_dir, settings.artifacts_dir/'report', model=settings.model, combined=args.combined, appendix='inline' if args.inline_appendix else 'separate', flows_file=settings.flows_file, ratings_file=settings.ratings_file)
        log.info('REPORT total=%s passed=%s failed=%s warnings=%s docs=%s', run.total, run.passed, run.failed, len(run.warnings), settings.artifacts_dir/'report')
        for warning in run.warnings:
            log.warning('REPORT WARNING %s', warning)
        if args.download and args.combined:
            _download_report(settings, log)
        if args.commit:
            _commit_site(settings, log, 'report')
        return result.returncode
    guide = (settings.root/'AI-TEST-GUIDE.md').read_text(encoding='utf-8') if (settings.root/'AI-TEST-GUIDE.md').exists() else ''
    persona = (settings.root/'persona.txt').read_text(encoding='utf-8') if (settings.root/'persona.txt').exists() else ''
    manifest = {'started_at': datetime.now(timezone.utc).isoformat(), 'urls': {}}; (settings.artifacts_dir/'run.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    client = ModelClient(settings, log)
    with sync_playwright() as pw:                             # a short-lived browser just for the session pre-check
        browser = pw.chromium.launch(headless=settings.headless)
        try:
            session = ensure_session(settings, browser, settings.seed_url or urls[0], log)
            if session.status in {'signed-in-env', 'signed-in-popup'}:
                pytest_env['WTP_STORAGE_STATE'] = str(session_path(settings))
        except Exception as exc:
            log.warning('auth: could not check for a login wall (%s)', str(exc).splitlines()[0][:150])
        finally:
            browser.close()
    # Each page gets its own thread, its own Playwright driver and its own browser (Playwright's sync API
    # is not safe to share across threads) - set GENERATE_CONCURRENCY=1 for the old one-page-at-a-time
    # behavior. The session pre-check above already wrote a storage_state file to disk if one was needed,
    # so every worker's context_kwargs() picks it up independently; no in-memory state is shared.
    concurrency = max(1, min(len(urls), int(os.environ.get('GENERATE_CONCURRENCY', '4') or '4')))
    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        futures = [pool.submit(_process_one_url, args.command, settings, client, guide, persona, url, i, len(urls), log, manifest)
                   for i, url in enumerate(urls)]
        for future in as_completed(futures):
            future.result()                                   # re-raise anything _process_one_url's own try/except missed
    manifest['finished_at'] = datetime.now(timezone.utc).isoformat(); manifest['summary'] = {'total':len(urls), 'generated':sum(x['status']=='generated' for x in manifest['urls'].values()), 'failed':sum(x['status']=='failed' for x in manifest['urls'].values())}; (settings.artifacts_dir/'run.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8'); summary = manifest['summary']; log.info('RUN SUMMARY total=%s generated=%s failed=%s', summary['total'], summary['generated'], summary['failed'])
    if args.commit and args.command == 'generate':
        _commit_site(settings, log, 'generate')
    return 1 if summary['failed'] else 0

if __name__ == '__main__': raise SystemExit(main())
