"""Turn verified flows into pytest specs with a template - no model involved.

A flow that `verify` ran already holds everything a test needs: the selectors and
values of each step and what the browser really showed afterwards. So the code is
emitted from that record, and every assertion comes from `flow["observed"]` (the
final URL, headings that appeared, a results region) - nothing is predicted.

A spec is written only if it passes the same validator as model-written specs; a
flow that cannot be turned into a strict test is skipped with the reason logged.
Files are named flow_<id>_test.py and carry a marker line so a re-run can remove
the ones whose flow is no longer emittable (rejected, changed) without touching
anything a person wrote.
"""
from __future__ import annotations
import re
from pathlib import Path
from types import SimpleNamespace

from .explorer import _plausible_value
from .flows import FlowsFileError, _slug, load_flows
from .runner import _path
from .sitemap import load_inventories
from .validator import SpecError, validate_python_spec, _norm

MARKER = "# generated by flowgen from flows.json - do not edit, re-run `flowgen`"
EMITTABLE = {"verified", "approved", "stale"}  # a stale flow keeps its test: failing is the alarm
_ROLE_ORDER = ("button", "link", "checkbox", "textbox")  # same order runner._locate tries
_TAG_ROLE = {"button": "button", "a": "link", "textarea": "textbox"}
_INPUT_ROLE = {"checkbox": "checkbox", "radio": "radio", "button": "button", "submit": "button"}
_NAME_CUT = 40          # flows store control names cut to 40 chars
_MAX_HEADINGS = 2


# ------------------------------------------------------------------ small helpers

def _lit(text: str) -> str:
    """A Python string literal; repr picks quotes so a selector like a[x="y"] stays readable."""
    return repr(text)


def _re_lit(pattern: str) -> str:
    return f'r"{pattern}"' if '"' not in pattern and "\\n" not in pattern and not pattern.endswith("\\") else _lit(pattern)


def _url_regex(path: str) -> str:
    """Matches the page at `path` whatever its query string or trailing slash."""
    if path == "/":
        return r"^https?://[^/]+/?(?:[?#].*)?$"
    return re.escape(path) + r"/?(?:[?#].*)?$"


def _role_of(control: dict) -> str | None:
    if control.get("role"):
        return str(control["role"]).lower()
    tag = control.get("tag")
    if tag == "input":
        typ = (control.get("type") or "text").lower()
        return _INPUT_ROLE.get(typ, "textbox")
    return _TAG_ROLE.get(tag or "")


def _distinct_word(text: str) -> str | None:
    words = re.findall(r"[^\W\d_]{5,}", text)
    return max(words, key=len) if words else None


def _control_pool(inventories: list[dict]) -> list[dict]:
    pool: list[dict] = []
    for inv in inventories:
        pool += inv.get("controls") or []
        for entry in inv.get("revealed") or []:
            pool += entry.get("controls") or []
    return pool


def _resolve_role(name: str, pool: list[dict]) -> str | None:
    """The role of the control called `name`, read from the explored pages. When the
    same name is both a button and a link, take the one the runner would have tried first."""
    wanted = _norm(name)[:_NAME_CUT]
    roles = {_role_of(c) for c in pool if _norm(c.get("name") or "")[:_NAME_CUT] == wanted}
    return next((r for r in _ROLE_ORDER if r in roles), None)


def _name_args(name: str) -> str:
    """get_by_role name arguments. A 40-char name was cut, so match its prefix."""
    if len(name) >= _NAME_CUT:
        return f"name=re.compile({_re_lit(re.escape(name))})"
    return f"name={_lit(name)}, exact=True"


def _locator(step: dict, pool: list[dict]) -> tuple[str | None, str]:
    if step.get("selector"):
        return f"page.locator({_lit(step['selector'])}).first", ""
    name = (step.get("name") or "").strip()
    if not name:
        return None, "a step has neither a selector nor a name"
    role = step.get("role") or _resolve_role(name, pool)
    if role is None:
        return None, f'cannot tell the role of "{name}" from the explored pages'
    return f"page.get_by_role({_lit(role)}, {_name_args(name)}).first", ""


def _target_slug(step: dict) -> str:
    return _slug(step.get("selector") or step.get("name") or "control", 24)


def _heading_locator(text: str) -> str | None:
    if len(text.split()) <= 6 and len(text) <= 70:
        return f"page.get_by_role('heading', name={_lit(text)}, exact=True).first"
    word = _distinct_word(text)
    return f"page.get_by_role('heading', name=re.compile({_lit(word)})).first" if word else None


def _stable_headings(observed: dict) -> list[str]:
    """Headings that appeared and are unlikely to rotate: not cut, no numbers in them."""
    out = []
    for h in observed.get("new_headings") or []:
        if 3 <= len(h) < 80 and not re.search(r"\d", h):
            out.append(h)
    return out[:_MAX_HEADINGS]


# ------------------------------------------------------------------ outcome assertions

def _outcome_expects(flow: dict, pool: list[dict]) -> tuple[list[str], list[dict], str]:
    """(expect(...) expressions, synthetic controls the validator must know, reason if none).
    Everything here is read from flow['observed']."""
    observed = flow["observed"]
    exprs: list[str] = []
    extra: list[dict] = []
    for h in _stable_headings(observed):
        loc = _heading_locator(h)
        if loc:
            exprs.append(f"expect({loc}).to_be_visible()")
            extra.append({"heading": h})
    for row in observed.get("results") or []:
        key = str(row.get("key") or "")
        if key[:1] in {"#", ".", "["} and len(key) > 1:
            exprs.append(f"expect(page.locator({_lit(key)}).first).to_be_visible()")
            extra.append({"results": key})
            break
    if not exprs and observed["effect"] == "reveals":
        for entry in observed.get("new_controls") or []:
            tag, _, name = entry.partition(":")
            role = _resolve_role(name, pool) if name and len(name) < _NAME_CUT else None
            if role:
                exprs.append(f"expect(page.get_by_role({_lit(role)}, name={_lit(name)}, exact=True).first).to_be_visible()")
                extra.append({"control": name, "role": role})
                break
    if not exprs and observed["effect"] != "navigates":
        return [], [], f'nothing stable to assert after a "{observed["effect"]}" outcome'
    return exprs, extra, ""


# ------------------------------------------------------------------ emitting one spec

def _step_verify(step: dict, effect: str | None, path_after: str | None, var: str) -> str:
    if effect == "navigates" and path_after:
        return f"expect(page).to_have_url(re.compile({_re_lit(_url_regex(path_after))}))"
    if effect != "navigates" and step.get("kind") == "select":
        return f'expect({var}).not_to_have_value("")'
    if effect != "navigates" and step.get("kind") == "fill":
        return f"expect({var}).to_have_value({_lit(str(step.get('value') or _plausible_value({})))})"
    if path_after:
        return f"expect(page).to_have_url(re.compile({_re_lit(_url_regex(path_after))}))"
    return 'expect(page.locator("body")).to_be_visible()'


def _step_action(step: dict, var: str) -> tuple[str | None, str]:
    kind = step.get("kind")
    if kind == "select":
        value = step.get("value")
        return (f"{var}.select_option(label={_lit(str(value))})" if value else f"{var}.select_option(index=1)"), ""
    if kind == "fill":
        return f"{var}.fill({_lit(str(step.get('value') or _plausible_value({})))})", ""
    if kind == "multiselect":
        if not step.get("value"):
            return None, "a multiselect step names no option to pick"
        return f"pick_option(page, {var}, {_lit(str(step['value']))})", ""
    if kind in {"click", "submit"}:
        return (f'{var}.press("Enter")' if step.get("value") == "press Enter" else f"{var}.click()"), ""
    return None, f"unknown step kind {kind!r}"


def _validation_inventory(flow: dict, inventories: list[dict], extra: list[dict]) -> SimpleNamespace:
    """What the validator may treat as observed: the explored pages this flow touches,
    plus the flow's own steps and what the run saw afterwards."""
    headings, controls = [], []
    forms, revealed, embeds, accessibility = [], [], [], []
    for inv in inventories:
        headings += inv.get("headings") or []
        controls += inv.get("controls") or []
        forms += inv.get("forms") or []
        revealed += inv.get("revealed") or []
        embeds += inv.get("embeds") or []
        accessibility.append(inv.get("accessibility") or "")
    results_selector = None
    for item in extra:
        if "heading" in item:
            headings.append({"text": item["heading"], "hidden": False})
        elif "control" in item:
            controls.append({"tag": "input", "name": item["control"], "role": item["role"]})
        elif "results" in item:
            results_selector = item["results"]
    return SimpleNamespace(
        url=flow["start_url"], headings=headings, controls=controls, forms=forms,
        revealed=revealed, embeds=embeds, accessibility="\n".join(accessibility),
        primary_flow={"steps": flow.get("steps") or [], "results_selector": results_selector},
    )


def _touched(flow: dict, inventories: list[dict]) -> list[dict]:
    pages = {_path(flow["start_url"]), _path((flow.get("observed") or {}).get("url") or "")}
    pages |= {_path(s["page"]) for s in flow.get("steps") or [] if s.get("page")}
    return [i for i in inventories if _path(i.get("url", "")) in pages]


def spec_test_name(flow: dict) -> str:
    return "test_flow_" + _slug(flow["id"], 70).replace("-", "_")


def file_name(flow: dict) -> str:
    return "flow_" + _slug(flow["id"], 80).replace("-", "_") + "_test.py"


def emit_flow_spec(flow: dict, inventories: list[dict]) -> tuple[str | None, str]:
    """(python source, '') for an emittable flow, else (None, reason)."""
    if flow.get("status") not in EMITTABLE:
        return None, f"status is {flow.get('status')!r} - only verified/approved/stale flows become tests"
    observed = flow.get("observed")
    if not observed:
        return None, "never run - run `verify` first"
    if observed.get("effect") == "no-visible-change":
        return None, "the run saw no visible change, so there is nothing to assert"
    steps = flow.get("steps") or []
    if not steps:
        return None, "flow has no steps"

    touched = _touched(flow, inventories)
    pool = _control_pool(touched)
    effects = list(observed.get("step_effects") or [])
    last_nav = max((i for i, e in enumerate(effects) if e == "navigates"), default=None)
    final_path = _path(observed.get("url") or "")
    # The start URL is not where the page stays (sat-stg redirects / to /en), so it is never used.
    # A run that recorded step_urls (step 10a) tells us the page after every step. An older run only
    # has the final URL: a path is then known only when no navigation happened, or after the last one.
    step_urls = list(observed.get("step_urls") or [])
    have_urls = len(step_urls) == len(steps)
    known_path: str | None = final_path if last_nav is None else None

    body: list[str] = []
    for i, step in enumerate(steps):
        locator, reason = _locator(step, pool)
        action, why = _step_action(step, "control")
        if locator is None or action is None:
            return None, reason or why
        effect = effects[i] if i < len(effects) else None
        if have_urls:
            known_path = _path(step_urls[i])
        elif effect == "navigates":
            known_path = final_path if i == last_nav else None
        label = f"{i + 1:02d}-{step.get('kind')}-{_target_slug(step)}"
        body += [
            f"    control = {locator}",
            "    action_evidence(",
            "        page,",
            f"        {_lit(label)},",
            f"        lambda: {action},",
            f"        lambda: {_step_verify(step, effect, known_path, 'control')},",
            "        evidence_dir,",
            "    )",
        ]

    exprs, extra, reason = _outcome_expects(flow, pool)
    if reason:
        return None, reason
    if exprs:
        body += ["    observation_evidence(", "        page,", "        '99-outcome',",
                 f"        lambda: {exprs[0]},", "        evidence_dir,", "    )"]
        body += [f"    {e}" for e in exprs[1:]]

    goal = re.sub(r"\s+", " ", flow.get("goal") or flow["id"]).replace("=", ":")[:200]
    source = "\n".join([
        MARKER, f"# Flow {flow['id']}: {goal}", "import re", "from pathlib import Path", "",
        "from playwright.sync_api import Page, expect",
        "from website_test_pipeline.evidence import action_evidence, observation_evidence",
        "from website_test_pipeline.pageutils import open_page, pick_option", "",
        f"URL = {_lit(flow['start_url'])}", "", "",
        "def _open(page: Page) -> None:", "    open_page(page, URL)", "", "",
        f"def {spec_test_name(flow)}(page: Page, evidence_dir: Path) -> None:", "    _open(page)", *body, "",
    ])
    try:
        validate_python_spec(source, flow["start_url"], _validation_inventory(flow, touched, extra))
    except SpecError as exc:
        return None, f"rejected by the spec validator: {exc}"
    return source, ""


# ------------------------------------------------------------------ command

def _stale_generated(tests_dir: Path, keep: set[str]) -> list[Path]:
    """flow_*_test.py files this tool wrote earlier whose flow no longer produces a spec."""
    stale = []
    for path in tests_dir.glob("flow_*_test.py"):
        if path.name in keep:
            continue
        try:
            if path.read_text(encoding="utf-8").startswith(MARKER):
                stale.append(path)
        except OSError:
            continue
    return stale


def run_flowgen(settings, log) -> int:
    try:
        doc = load_flows(settings.flows_file)
    except FlowsFileError as exc:
        log.error("flowgen: %s", exc)
        return 1
    if not doc["flows"]:
        log.error("flowgen: no flows in %s - run explore or propose, then verify", settings.flows_file)
        return 2
    inventories = load_inventories(settings.artifacts_dir)
    settings.tests_dir.mkdir(parents=True, exist_ok=True)
    written: set[str] = set()
    skipped = 0
    for flow in doc["flows"]:
        source, reason = emit_flow_spec(flow, inventories)
        if source is None:
            skipped += 1
            log.info("flowgen: skipped %s (%s)", flow["id"], reason)
            continue
        name = file_name(flow)
        (settings.tests_dir / name).write_text(source, encoding="utf-8")
        written.add(name)
        log.info("flowgen: wrote %s", name)
    for path in _stale_generated(settings.tests_dir, written):
        path.unlink()
        log.info("flowgen: removed %s (its flow no longer produces a spec)", path.name)
    log.info("FLOWGEN SUMMARY flows=%d written=%d skipped=%d dir=%s",
             len(doc["flows"]), len(written), skipped, settings.tests_dir)
    return 0
