import { readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TEST_ROOT = resolve(ROOT, 'tests');
const requested = process.argv.slice(2);
function inside(p, root) { const r = relative(root, p); return r && !r.startsWith('..') && !r.includes('\0'); }
function filesFor(args) {
  if (!args.length) return readdirSync(TEST_ROOT).filter(n => n.endsWith('.spec.ts')).map(n => resolve(TEST_ROOT,n));
  const out=[]; for (const arg of args) { if (arg.includes('*')) { const names=readdirSync(TEST_ROOT); const re=new RegExp('^'+arg.replace(/^tests\//,'').replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*')+'$'); for(const n of names) if(re.test(n)) out.push(resolve(TEST_ROOT,n)); } else { const p=resolve(ROOT,arg); if(!inside(p,TEST_ROOT)) throw new Error(`Refusing path outside tests/: ${arg}`); out.push(p); } } return [...new Set(out)];
}
const files=filesFor(requested); const behaviorWords=/\b(allow|navigat\w*|switch\w*|select\w*|submit\w*|open\w*|interact\w*|search\w*|change\w*|filter\w*|validat\w*|toggle\w*|functional)\b/i; const action=/\.(click|selectOption|fill|check|uncheck|press|setInputFiles|hover)\s*\(/; const evidence=/actionEvidence\s*\(/; const meaningful=/toHaveURL|toHaveValue|toHaveText|toContainText|toBeVisible|toHaveCount|toBeEnabled|toBeChecked|toBeGreaterThan/; const validAction=/actionEvidence\s*\(\s*page\s*,\s*testInfo\s*,/; const validObs=/observationEvidence\s*\(\s*page\s*,\s*testInfo\s*,/; const generic=/^(should\s+)?(work|works|display correctly|displays correctly|functional navigation|selects a country and channel)$/i; const failures=[];
for(const file of files){const code=readFileSync(file,'utf8'); if(/:has-text\s*\(|locator\(\s*['"]text=|getByText\s*\(/.test(code)) failures.push(`${file}: unstable text selector`); if(evidence.test(code)&&!validAction.test(code)&&!validObs.test(code)) failures.push(`${file}: invalid evidence helper signature`); if(!/test\.describe\s*\(\s*['"]https?:\/\//.test(code)) failures.push(`${file}: missing full URL in test.describe`); for(const block of code.split(/(?=\btest\s*\()/).filter(Boolean)){const title=block.match(/test\s*\(\s*['"]([^'"]+)/)?.[1]||''; if(behaviorWords.test(title)&&action.test(block)&&!evidence.test(block)) failures.push(`${file}: "${title}" performs action without evidence`); if(behaviorWords.test(title)&&action.test(block)&&!meaningful.test(block)&&!/NOT TESTABLE/i.test(block)) failures.push(`${file}: "${title}" has no meaningful postcondition`); if(generic.test(title.trim())) failures.push(`${file}: generic test title "${title}"`);}}
if(failures.length){console.error(failures.map(x=>`  - ${x}`).join('\n'));process.exit(1)} console.log(`Validated ${files.length} spec file(s).`);